/*
 Navicat Premium Data Transfer

 Source Server         : sociotechnical.ischool.drexel.edu
 Source Server Type    : MySQL
 Source Server Version : 50167
 Source Host           : sociotechnical.ischool.drexel.edu
 Source Database       : philasd

 Target Server Type    : MySQL
 Target Server Version : 50167
 File Encoding         : utf-8

 Date: 02/23/2013 14:32:49 PM
*/

SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
--  Table structure for `SCHOOL_ENROLLMENT`
-- ----------------------------
DROP TABLE IF EXISTS `SCHOOL_ENROLLMENT`;
CREATE TABLE `SCHOOL_ENROLLMENT` (
  `SCHOOL_CODE` int(11) DEFAULT NULL,
  `SCHOOL_YEAR` varchar(255) DEFAULT NULL,
  `SCH_ATTENDANCE` float DEFAULT NULL,
  `SCH_ENROLLMENT` int(11) DEFAULT NULL,
  `SCH_STUDENT_ENTERED` int(11) DEFAULT NULL,
  `SCH_STUDENT_WITHDREW` int(11) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `SCHOOL_ETHNICITY_LOW_INCOME`
-- ----------------------------
DROP TABLE IF EXISTS `SCHOOL_ETHNICITY_LOW_INCOME`;
CREATE TABLE `SCHOOL_ETHNICITY_LOW_INCOME` (
  `SCHOOL_CODE` int(11) DEFAULT NULL,
  `SCHOOL_YEAR` varchar(255) DEFAULT NULL,
  `AFRICAN_AMERICAN` float DEFAULT NULL,
  `WHITE` float DEFAULT NULL,
  `ASIAN` float DEFAULT NULL,
  `LATINO` float DEFAULT NULL,
  `OTHER` float DEFAULT NULL,
  `PACIFIC_ISLANDER` int(11) DEFAULT NULL,
  `AMERICAN_INDIAN` float DEFAULT NULL,
  `SCH_LOW_INCOME_FAMILY` float DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `SCHOOL_INFORMATION`
-- ----------------------------
DROP TABLE IF EXISTS `SCHOOL_INFORMATION`;
CREATE TABLE `SCHOOL_INFORMATION` (
  `SCHOOL_CODE` int(11) DEFAULT NULL,
  `SCHOOL_NAME_1` varchar(255) DEFAULT NULL,
  `SCHOOL_NAME_2` varchar(255) DEFAULT NULL,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `SCHOOL_ZIP` int(11) DEFAULT NULL,
  `ZIP_PLUS_4` varchar(255) DEFAULT NULL,
  `CITY` varchar(255) DEFAULT NULL,
  `STATE_CD` varchar(255) DEFAULT NULL,
  `PHONE_NUMBER` int(11) DEFAULT NULL,
  `SCH_START_GRADE` int(11) DEFAULT NULL,
  `SCH_TERM_GRADE` int(11) DEFAULT NULL,
  `HPADDR` varchar(255) DEFAULT NULL,
  `SCHOOL_LEVEL_NAME` varchar(255) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `SCHOOL_PSSA`
-- ----------------------------
DROP TABLE IF EXISTS `SCHOOL_PSSA`;
CREATE TABLE `SCHOOL_PSSA` (
  `SCHOOL_CODE` int(11) DEFAULT NULL,
  `SCHOOL_YEAR` varchar(255) DEFAULT NULL,
  `GRADE` int(11) DEFAULT NULL,
  `MATH_ADVANCED_PERCENT` varchar(255) DEFAULT NULL,
  `MATH_PROFICIENT_PERCENT` varchar(255) DEFAULT NULL,
  `MATH_BASIC_PERCENT` varchar(255) DEFAULT NULL,
  `MATH_BELOW_BASIC_PERCENT` varchar(255) DEFAULT NULL,
  `READ_ADVANCED_PERCENT` varchar(255) DEFAULT NULL,
  `READ_PROFICIENT_PERCENT` varchar(255) DEFAULT NULL,
  `READ_BASIC_PERCENT` varchar(255) DEFAULT NULL,
  `READ_BELOW_BASIC_PERCENT` varchar(255) DEFAULT NULL,
  `MATH_COMBINED_PERCENT` varchar(255) DEFAULT NULL,
  `READ_COMBINED_PERCENT` varchar(255) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `SCHOOL_SERIOUS_INCIDENTS`
-- ----------------------------
DROP TABLE IF EXISTS `SCHOOL_SERIOUS_INCIDENTS`;
CREATE TABLE `SCHOOL_SERIOUS_INCIDENTS` (
  `ULCS_NO` int(11) DEFAULT NULL,
  `SCHOOL_YEAR` varchar(255) DEFAULT NULL,
  `ASSAULT` int(11) DEFAULT NULL,
  `DRUG` int(11) DEFAULT NULL,
  `MORALS` int(11) DEFAULT NULL,
  `WEAPONS` int(11) DEFAULT NULL,
  `THEFT` int(11) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `SCHOOL_STUDENT`
-- ----------------------------
DROP TABLE IF EXISTS `SCHOOL_STUDENT`;
CREATE TABLE `SCHOOL_STUDENT` (
  `SCHOOL_CODE` int(11) DEFAULT NULL,
  `SCHOOL_YEAR` varchar(255) DEFAULT NULL,
  `SCH_SPEC_ED_SERVICES` float DEFAULT NULL,
  `SCH_MG` float DEFAULT NULL,
  `SCH_ESOL_SERVICES` float DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `SCHOOL_SUSPENSIONS`
-- ----------------------------
DROP TABLE IF EXISTS `SCHOOL_SUSPENSIONS`;
CREATE TABLE `SCHOOL_SUSPENSIONS` (
  `SCHOOL_CODE` int(11) DEFAULT NULL,
  `SCHOOL_YEAR` varchar(255) DEFAULT NULL,
  `TOTAL_SUSPENSIONS` int(11) DEFAULT NULL,
  `SCH_ONE_TIME_SUSP` int(11) DEFAULT NULL,
  `SCH_TWO_TIME_SUSP` int(11) DEFAULT NULL,
  `SCH_THREE_TIME_SUSP` int(11) DEFAULT NULL,
  `SCH_MORE_THAN_THREE_SUSP` int(11) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- ----------------------------
--  Table structure for `TEACHER_ATTEND`
-- ----------------------------
DROP TABLE IF EXISTS `TEACHER_ATTEND`;
CREATE TABLE `TEACHER_ATTEND` (
  `SCHOOL_CODE` int(11) DEFAULT NULL,
  `SCHOOL_YEAR` varchar(255) DEFAULT NULL,
  `SCH_TEACHER_ATTEND` float DEFAULT NULL,
  `SDP_TEACHER_ATTEND_AVG` float DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS = 1;
