SELECT
	SCHOOL_INFORMATION.SCHOOL_CODE,
	SCHOOL_INFORMATION.SCHOOL_NAME_1,
	SCHOOL_INFORMATION.SCH_START_GRADE,
	SCHOOL_INFORMATION.SCH_TERM_GRADE,
	SCHOOL_INFORMATION.SCHOOL_LEVEL_NAME,
	SCHOOL_SERIOUS_INCIDENTS.SCHOOL_YEAR,
	SCHOOL_SERIOUS_INCIDENTS.ASSAULT,
	SCHOOL_SERIOUS_INCIDENTS.DRUG,
	SCHOOL_SERIOUS_INCIDENTS.MORALS,
	SCHOOL_SERIOUS_INCIDENTS.THEFT,
	SCHOOL_SUSPENSIONS.TOTAL_SUSPENSIONS,
	SCHOOL_ETHNICITY_LOW_INCOME.SCH_LOW_INCOME_FAMILY
FROM
	SCHOOL_INFORMATION
LEFT OUTER JOIN SCHOOL_SERIOUS_INCIDENTS ON SCHOOL_INFORMATION.SCHOOL_CODE = SCHOOL_SERIOUS_INCIDENTS.ULCS_NO
LEFT OUTER JOIN SCHOOL_SUSPENSIONS ON SCHOOL_SERIOUS_INCIDENTS.ULCS_NO = SCHOOL_SUSPENSIONS.SCHOOL_CODE 
 INNER JOIN SCHOOL_ETHNICITY_LOW_INCOME on SCHOOL_SERIOUS_INCIDENTS.ULCS_NO = SCHOOL_ETHNICITY_LOW_INCOME.SCHOOL_CODE 
AND SCHOOL_SERIOUS_INCIDENTS.SCHOOL_YEAR = SCHOOL_SUSPENSIONS.SCHOOL_YEAR
AND SCHOOL_SERIOUS_INCIDENTS.SCHOOL_YEAR = SCHOOL_ETHNICITY_LOW_INCOME.SCHOOL_YEAR
AND SCHOOL_SUSPENSIONS.SCHOOL_YEAR = SCHOOL_ETHNICITY_LOW_INCOME.SCHOOL_YEAR
ORDER BY
	SCHOOL_INFORMATION.SCHOOL_CODE,
	SCHOOL_SERIOUS_INCIDENTS.SCHOOL_YEAR