SELECT
	SCHOOL_INFORMATION.SCHOOL_CODE,
	SCHOOL_INFORMATION.SCHOOL_NAME_1,
	SCHOOL_INFORMATION.SCH_START_GRADE,
	SCHOOL_INFORMATION.SCH_TERM_GRADE,
	SCHOOL_ENROLLMENT.SCHOOL_YEAR,
	SCHOOL_ENROLLMENT.SCH_ATTENDANCE,
	SCHOOL_ENROLLMENT.SCH_ENROLLMENT,
	SCHOOL_ENROLLMENT.SCH_STUDENT_ENTERED,
	SCHOOL_ENROLLMENT.SCH_STUDENT_WITHDREW,
	TEACHER_ATTEND.SCH_TEACHER_ATTEND,
	TEACHER_ATTEND.SDP_TEACHER_ATTEND_AVG
FROM
	SCHOOL_INFORMATION
LEFT OUTER JOIN SCHOOL_ENROLLMENT ON SCHOOL_INFORMATION.SCHOOL_CODE = SCHOOL_ENROLLMENT.SCHOOL_CODE
LEFT OUTER JOIN TEACHER_ATTEND ON SCHOOL_ENROLLMENT.SCHOOL_CODE = TEACHER_ATTEND.SCHOOL_CODE
AND SCHOOL_ENROLLMENT.SCHOOL_YEAR = TEACHER_ATTEND.SCHOOL_YEAR
ORDER BY
	SCHOOL_INFORMATION.SCHOOL_CODE,
	SCHOOL_ENROLLMENT.SCHOOL_YEAR